FROM amazoncorretto:17-alpine
COPY lojaremedio.jar lojaremedio.jar
ENTRYPOINT [ "java", "-jar", "/lojaremedio.jar" ]
# docker build -t cesar/vacina-server .
# docker network create cesar-ms-network
# docker run --network cesar-ms-network cesar/vacina-server