spring:
  application:
    name: LOJA-VENDA-SERVICE
  main:
    allow-bean-definition-overriding: true
  datasource:
    hibernate:
      ddl-auto: update
    url: jdbc:postgresql://postgresql:5432/postgres
    #url: jdbc:localhost://postgresql:5432/postgres
    username: postgres
    password: 654321
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
      #defaultZone: http://localhost:8761/eureka
server:
  port: 8281
logging:
  .pattern:
    level: 5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]
management:
  zipkin:
    tracing:
       endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0